# Generated by Django 4.2.4 on 2023-08-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookStoreModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(default='Unknown book', max_length=100)),
                ('author', models.CharField(default='Unknown', max_length=25)),
                ('category', models.CharField(choices=[('Mystery', 'Mystery'), ('Thriller', 'Thriller'), ('Sci-Fi', 'Sci-Fi'), ('Humor', 'Humor'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Westerns', 'Westerns'), ('Biographies', 'Biographies'), ('History', 'History'), ('Cookbooks', 'Cookbooks'), ('Poetry', 'Poetry'), ('True Crime', 'True Crime'), ('Drama', 'Drama'), ('Action', 'Action'), ('Adventure', 'Adventure'), ('Satire', 'Satire'), ('Anthology', 'Anthology')], max_length=25)),
                ('first_published', models.DateTimeField(auto_now_add=True)),
                ('last_published', models.DateTimeField()),
            ],
        ),
    ]
