# Generated by Django 4.2.4 on 2023-08-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_bookstoremodel_last_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstoremodel',
            name='first_published',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookstoremodel',
            name='last_published',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
