# Generated by Django 4.2.4 on 2023-08-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_bookstoremodel_first_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstoremodel',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
